sudo: required
services:
  - docker

before_install:
  - docker build -t nielsgroen/docker-react-test -f Dockerfile.dev .

script:
  - docker run nielsgroen/docker-react-test npm run test -- --coverage